{
 "title": "Python Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 30, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{source=\"PythonApp\"}"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n  {source=\"PythonApp\"} \n  | logfmt \n  | code = 202\n  [1h]\n  )\n)"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n  {source=\"PythonApp\"} \n  | logfmt \n  | code = 201 \n  [1h]\n  )\n)"
    }
   ]
  },
  {
   "title": "INFO",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n  {source=\"PythonApp\"} \n  | logfmt \n  | code = 200 \n  [1h]\n  )\n)"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "{source=\"PythonApp\"}\n| logfmt \n| code = 202"
    }
   ]
  },
  {
   "title": "USER 1",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 11, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n  {source=\"PythonApp\"} \n  | logfmt \n  | userId = 1\n  [1h]\n  )\n)"
    }
   ]
  },
  {
   "title": "USER 2",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n  {source=\"PythonApp\"} \n  | logfmt \n  | userId = 2\n  [1h]\n  )\n)"
    }
   ]
  },
  {
   "title": "USER 3",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n  {source=\"PythonApp\"} \n  | logfmt \n  | userId = 3\n  [1h]\n  )\n)"
    }
   ]
  }
 ]
}